// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.datacontext;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240617193457_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web.models.MainList", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("mainList");
                });

            modelBuilder.Entity("webapi.models.kitchen.Aromatics", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("mainListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("mainListId")
                        .IsUnique();

                    b.ToTable("aromatics");
                });

            modelBuilder.Entity("webapi.models.kitchen.Aromatics", b =>
                {
                    b.HasOne("web.models.MainList", "mainList")
                        .WithOne("aromatics")
                        .HasForeignKey("webapi.models.kitchen.Aromatics", "mainListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mainList");
                });

            modelBuilder.Entity("web.models.MainList", b =>
                {
                    b.Navigation("aromatics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
